import { useMemo, useState } from "react";
import "./SalaryPredictorPage.css";

function SalaryPredictorPage() {
  const user = JSON.parse(localStorage.getItem("user") || "{}");
  const candidateName = user?.name || user?.fullName || "Candidate";

  const [role, setRole] = useState("Data Engineer");
  const [experience, setExperience] = useState("3-5 Years");
  const [location, setLocation] = useState("Bangalore, India");
  const [employmentType, setEmploymentType] = useState("Full-time");
  const [skills, setSkills] = useState("Python, SQL, AWS, Snowflake, Apache Spark");
  const [result, setResult] = useState(null);

  const salaryData = {
    "Data Engineer": { base: 15.9, high: 32.7 },
    "Frontend Developer": { base: 10.8, high: 24.5 },
    "Backend Developer": { base: 13.2, high: 28.4 },
    "Full Stack Developer": { base: 14.5, high: 30.8 },
    "DevOps Engineer": { base: 16.7, high: 35.2 },
    "Data Scientist": { base: 18.2, high: 38.5 },
    "SAP Consultant": { base: 14.8, high: 31.2 },
    "Cybersecurity Analyst": { base: 17.5, high: 36.9 },
  };

  const expMultiplier = {
    "0-1 Years": 0.55,
    "1-3 Years": 0.78,
    "3-5 Years": 1,
    "5-8 Years": 1.35,
    "8+ Years": 1.75,
  };

  const locationMultiplier = {
    "Bangalore, India": 1.12,
    "Hyderabad, India": 1.05,
    "Pune, India": 1,
    "Chennai, India": 0.94,
    "Mumbai, India": 1.08,
    "Delhi NCR, India": 1.04,
    "Remote": 1.02,
  };

  function parseSkills() {
    return skills
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
  }

  function predictSalary() {
    const baseInfo = salaryData[role] || salaryData["Data Engineer"];
    const skillList = parseSkills();

    const premiumSkills = [
      "AWS",
      "Azure",
      "GCP",
      "Snowflake",
      "Databricks",
      "Apache Spark",
      "PySpark",
      "Kubernetes",
      "Terraform",
      "Kafka",
      "Machine Learning",
      "Cybersecurity",
    ];

    const premiumCount = skillList.filter((skill) =>
      premiumSkills.some((p) => p.toLowerCase() === skill.toLowerCase())
    ).length;

    const skillBoost = Math.min(premiumCount * 0.08, 0.35);
    const expBoost = expMultiplier[experience] || 1;
    const locBoost = locationMultiplier[location] || 1;
    const empBoost = employmentType === "Contract" ? 1.18 : employmentType === "Internship" ? 0.35 : 1;

    const estimated = Number(
      (baseInfo.base * expBoost * locBoost * empBoost * (1 + skillBoost)).toFixed(1)
    );

    const min = Number((estimated * 0.66).toFixed(1));
    const max = Number((estimated * 1.49).toFixed(1));
    const percentile = Math.min(96, Math.round(55 + premiumCount * 5 + (expBoost - 1) * 20));
    const growth = Number((estimated * 1.54).toFixed(1));

    setResult({
      estimated,
      min,
      max,
      percentile,
      marketAverage: baseInfo.base,
      highPerformer: baseInfo.high,
      growth,
      demand: estimated > 18 ? "Very High" : estimated > 12 ? "High" : "Medium",
      jobs: Math.round(6200 + estimated * 350),
      skills: skillList,
    });
  }

  function downloadReport() {
    if (!result) {
      alert("Please predict salary first.");
      return;
    }

    const report = `
NoPromptJobs - AI Salary Prediction Report

Candidate: ${candidateName}
Role: ${role}
Experience: ${experience}
Location: ${location}
Employment Type: ${employmentType}
Skills: ${skills}

Estimated Salary: ₹${result.estimated} LPA
Minimum Range: ₹${result.min} LPA
Maximum Range: ₹${result.max} LPA
Market Average: ₹${result.marketAverage} LPA
Top 10% Earn: ₹${result.highPerformer} LPA
Growth Potential: ₹${result.growth} LPA
Market Percentile: ${result.percentile}%
Demand Level: ${result.demand}
Job Opportunities: ${result.jobs}

Generated by NoPromptJobs AI Salary Predictor.
`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");

    a.href = url;
    a.download = "salary-prediction-report.txt";
    a.click();

    URL.revokeObjectURL(url);
  }

  function goTo(path) {
    window.location.href = path;
  }

  const display = result || {
    estimated: 0,
    min: 0,
    max: 0,
    percentile: 0,
    marketAverage: 0,
    highPerformer: 0,
    growth: 0,
    demand: "Pending",
    jobs: 0,
    skills: [],
  };

  const trend = useMemo(() => {
    if (!result) return [0, 0, 0, 0, 0];
    return [
      result.estimated * 0.82,
      result.estimated * 0.96,
      result.estimated * 1.11,
      result.estimated * 1.3,
      result.growth,
    ].map((v) => Number(v.toFixed(1)));
  }, [result]);

  return (
    <main className="sp-page">
      <aside className="sp-sidebar">
        <div className="sp-brand">
          <img src="/logo.png" alt="NoPromptJobs" />
          <div>
            <h2>NoPromptJobs</h2>
            <p>AI CAREER COPILOT</p>
          </div>
        </div>

       <nav className="sp-menu">
  <button onClick={() => goTo("/ultimate-dashboard")}>
    🏠 Dashboard
  </button>

  <button onClick={() => goTo("/resume-studio")}>
    📄 AI Resume Review
  </button>

  <button onClick={() => goTo("/skill-analyzer")}>
    📊 Skill Analyzer
  </button>

  <button onClick={() => goTo("/career-roadmap")}>
    🧭 AI Career Roadmap
  </button>

  <button className="active">
    💰 Salary Predictor
  </button>

  <button onClick={() => goTo("/jobs")}>
    💼 Job Matcher
  </button>

  <button onClick={() => goTo("/ai-interview-prep")}>
    🎤 Interview Prep
  </button>

  <button
    onClick={() =>
      goTo("/ai-interview-prep?tab=Question%20Bank")
    }
  >
    📚 Question Bank
  </button>

  <button onClick={() => goTo("/applications")}>
    📂 My Applications
  </button>

  <button
    onClick={() =>
      goTo("/ai-interview-prep?tab=My%20Reports")
    }
  >
    📈 Reports
  </button>
</nav>

<div className="sp-profile">
  <span>{candidateName.slice(0, 2).toUpperCase()}</span>

  <div>
    <b>{candidateName}</b>
    <p>{role}</p>
  </div>
</div>      </aside>

      <section className="sp-main">
        <header className="sp-header">
          <div>
            <h1>AI Salary Predictor</h1>
            <p>
              Get AI-powered salary predictions based on your skills,
              experience, location and market trends.
            </p>
          </div>

          <button onClick={downloadReport}>⬇ Download Report</button>
          <div className="sp-bell">🔔</div>
          <div className="sp-avatar">{candidateName.slice(0, 2).toUpperCase()}</div>
        </header>

        <section className="sp-top-grid">
          <div className="sp-card sp-form-card">
            <h2>Enter Your Details</h2>

            <div className="sp-form-grid">
              <label>
                Target Role
                <select value={role} onChange={(e) => setRole(e.target.value)}>
                  {Object.keys(salaryData).map((item) => (
                    <option key={item}>{item}</option>
                  ))}
                </select>
              </label>

              <label>
                Experience
                <select value={experience} onChange={(e) => setExperience(e.target.value)}>
                  <option>0-1 Years</option>
                  <option>1-3 Years</option>
                  <option>3-5 Years</option>
                  <option>5-8 Years</option>
                  <option>8+ Years</option>
                </select>
              </label>

              <label>
                Location
                <select value={location} onChange={(e) => setLocation(e.target.value)}>
                  {Object.keys(locationMultiplier).map((item) => (
                    <option key={item}>{item}</option>
                  ))}
                </select>
              </label>

              <label>
                Employment Type
                <select value={employmentType} onChange={(e) => setEmploymentType(e.target.value)}>
                  <option>Full-time</option>
                  <option>Contract</option>
                  <option>Internship</option>
                </select>
              </label>
            </div>

            <label className="sp-full-label">
              Skills
              <textarea
                value={skills}
                onChange={(e) => setSkills(e.target.value)}
                placeholder="Python, SQL, AWS, Spark, Snowflake..."
              />
            </label>

            <button className="sp-primary" onClick={predictSalary}>
              ✨ Predict Salary
            </button>
          </div>

          <div className="sp-card sp-report-card">
            <h2>Predicted Salary Report</h2>

            {!result ? (
              <div className="sp-empty">AI salary prediction will appear here.</div>
            ) : (
              <>
                <p>Estimated Annual Salary</p>
                <h3>₹ {display.estimated} LPA <span>↑ 16%</span></h3>

                <div className="sp-range-bar">
                  <i></i>
                </div>

                <div className="sp-range-values">
                  <p>₹{display.min} LPA <span>Min Range</span></p>
                  <p>₹{display.estimated} LPA <span>Estimated</span></p>
                  <p>₹{display.max} LPA <span>Max Range</span></p>
                </div>

                <div className="sp-percent-ring">
                  <strong>{display.percentile}%</strong>
                  <span>Market Percentile</span>
                </div>
              </>
            )}
          </div>
        </section>

        <section className="sp-kpi-grid">
          <div className="sp-kpi"><span>🎯</span><p>Market Average</p><h3>₹{display.marketAverage} LPA</h3></div>
          <div className="sp-kpi"><span>🛡</span><p>Top 10% Earn</p><h3>₹{display.highPerformer} LPA</h3></div>
          <div className="sp-kpi"><span>🚀</span><p>Growth Potential</p><h3>₹{display.growth} LPA</h3></div>
          <div className="sp-kpi"><span>📈</span><p>Demand Level</p><h3>{display.demand}</h3></div>
          <div className="sp-kpi"><span>💼</span><p>Job Opportunities</p><h3>{display.jobs.toLocaleString()}</h3></div>
        </section>

        <section className="sp-bottom-grid">
          <div className="sp-card">
            <h2>Salary Breakdown</h2>
            <div className="sp-donut">
              <strong>₹{display.estimated}</strong>
              <span>Total Package</span>
            </div>
            {[
              ["Base Salary", 65],
              ["Performance Bonus", 13],
              ["Stock / RSU", 11],
              ["Other Benefits", 10],
            ].map(([label, value]) => (
              <div className="sp-row" key={label}>
                <p>{label}</p>
                <b>{value}%</b>
              </div>
            ))}
          </div>

          <div className="sp-card sp-trend-card">
            <h2>Salary Trends</h2>
            <div className="sp-trend-line">
              {trend.map((item, index) => (
                <div key={index}>
                  <span style={{ height: `${Math.max(item * 5, 10)}px` }}></span>
                  <b>₹{item}</b>
                  <p>{index + 1} YR</p>
                </div>
              ))}
            </div>
          </div>

          <div className="sp-card">
            <h2>Top Paying Companies</h2>
            {[
              ["Google", 28.7],
              ["Microsoft", 24.5],
              ["Amazon", 22.8],
              ["Snowflake", 21.6],
              ["Adobe", 20.3],
            ].map(([company, pay]) => (
              <button className="sp-company" key={company} onClick={() => alert(`${company} salary benchmark: ₹${pay} LPA`)}>
                <span>{company}</span>
                <b>₹{pay} LPA ›</b>
              </button>
            ))}
          </div>
        </section>
      </section>
    </main>
  );
}

export default SalaryPredictorPage;